--------------------------------------------------------
-- Archivo creado  - miércoles-abril-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for DB Link DB
--------------------------------------------------------

  CREATE DATABASE LINK "DB"
   CONNECT TO "C##PROYECTDB" IDENTIFIED BY VALUES ':1'
   USING '
    (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.19.1)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = WEBSOLS)
    )
  )';
--------------------------------------------------------
--  DDL for Table CATALOGO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CATALOGO" 
   (	"COD_TABLA" NUMBER(2,0), 
	"CODIGO" CHAR(1), 
	"VALOR" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CL_CIUDAD
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CL_CIUDAD" 
   (	"CD_IDCIUDAD" NUMBER(3,0), 
	"CD_IDDEPTO" NUMBER(3,0), 
	"CD_IDPAIS" NUMBER(3,0), 
	"CD_CIUDAD" NVARCHAR2(32)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CL_CLIENTE
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CL_CLIENTE" 
   (	"CL_IDCLIENTE" NUMBER(*,0), 
	"CL_TIPODOCUMENTO" CHAR(1), 
	"CL_NUMDOCUMENTO" NUMBER(*,0), 
	"CL_NOMBRES" NVARCHAR2(64), 
	"CL_PAPELLIDO" NVARCHAR2(32), 
	"CL_SAPELLIDO" NVARCHAR2(32), 
	"CL_PROFESION" NUMBER(2,0), 
	"CL_EMAIL" NVARCHAR2(32), 
	"CL_ESTADO" CHAR(1), 
	"CL_TIPOCLIENTE" CHAR(1), 
	"CL_IDENTTRIBUTARIA" NUMBER(*,0), 
	"CL_USUARIO" NVARCHAR2(16), 
	"CL_CLAVE" NVARCHAR2(16), 
	"CL_FECHA_REGISTRO" DATE, 
	"CL_FECHA_BAJA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CL_DEPTO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CL_DEPTO" 
   (	"DP_IDDEPTO" NUMBER(3,0), 
	"DP_IDPAIS" NUMBER(3,0), 
	"DP_DEPTO" NVARCHAR2(32)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CL_DIRECCION
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CL_DIRECCION" 
   (	"DI_TIPODIRECCION" CHAR(1), 
	"DI_CLIENTE" NUMBER(*,0), 
	"DI_DIRECCION" NVARCHAR2(64), 
	"DI_CIUDAD" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CL_PAIS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CL_PAIS" 
   (	"PA_IDPAIS" NUMBER(3,0), 
	"PA_PAIS" NVARCHAR2(32), 
	"PA_IDIDIOMA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CL_PROFESION
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CL_PROFESION" 
   (	"PR_IDPROFESION" NUMBER(3,0), 
	"PR_PROFESION" NVARCHAR2(32)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CL_TELEFONO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."CL_TELEFONO" 
   (	"TE_TIPOTELEFONO" CHAR(1), 
	"TE_IDCLIENTE" NUMBER(*,0), 
	"TE_TELEFONO" NVARCHAR2(16)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EM_CARGO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."EM_CARGO" 
   (	"CAR_IDCARGO" NUMBER(3,0), 
	"CAR_CARGO" NVARCHAR2(64), 
	"CAR_CARGO_SUP" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EM_EMPLEADO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."EM_EMPLEADO" 
   (	"EM_CODPLANILLA" NUMBER(3,0), 
	"EM_NOMBRES" NVARCHAR2(64), 
	"EM_PAPELLIDO" NVARCHAR2(32), 
	"EM_SAPELLIDO" NVARCHAR2(32), 
	"EM_FECHA_ING" DATE, 
	"EM_FECHA_FIN" DATE, 
	"EM_SUELDO" NUMBER(6,0), 
	"EM_SUPERIOR" NUMBER(3,0), 
	"EM_TIENDA" NUMBER(3,0), 
	"EM_CARGO" NUMBER(3,0), 
	"EM_ESTADO" NUMBER(3,0), 
	"EM_CLAVE" NVARCHAR2(16), 
	"EM_LOGIN" NVARCHAR2(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PR_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."PR_CATEGORIA" 
   (	"CA_IDCATEGORIA" NUMBER(3,0), 
	"CA_CATEGORIA" NVARCHAR2(32), 
	"CA_IDPADRE" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PR_DESCUENTO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."PR_DESCUENTO" 
   (	"DE_IDDESCUENTO" NUMBER(3,0), 
	"DE_PORCENTAJE" NUMBER(3,0), 
	"DE_FECHA_INICIO" DATE, 
	"DE_FECHA_FIN" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PR_FABRICANTE
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."PR_FABRICANTE" 
   (	"FA_IDFABRICANTE" NUMBER(3,0), 
	"FA_FABRICANTE" NVARCHAR2(32), 
	"FA_IDPROVEEDOR" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PR_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."PR_PRODUCTO" 
   (	"PR_IDPRODUCTO" NUMBER(3,0), 
	"PR_DESCRIPCION" NVARCHAR2(32), 
	"PR_PRECIO" NUMBER(3,2), 
	"PR_CANTMINIMA" NUMBER(4,0), 
	"PR_ESTADO" CHAR(1), 
	"PR_MODELO" NVARCHAR2(64), 
	"PR_IDFABRICANTE" NUMBER(3,0), 
	"PR_IDCATEGORIA" NUMBER(3,0), 
	"PR_IDDESCUENTO" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PR_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."PR_PROVEEDOR" 
   (	"PRO_IDPROVEEDOR" NUMBER(3,0), 
	"PRO_PROVEEDOR" NVARCHAR2(32)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PR_TIENDA
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."PR_TIENDA" 
   (	"TI_IDTIENDA" NUMBER(3,0), 
	"TI_TIENDA" NVARCHAR2(32), 
	"TI_DIRECCION" NVARCHAR2(64), 
	"TI_IDCIUDAD" NUMBER(3,0), 
	"TI_TELEFONO" NUMBER(16,0), 
	"TI_NIT" NVARCHAR2(32)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PR_TIENDA_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."PR_TIENDA_PRODUCTO" 
   (	"TP_IDTIENDA" NUMBER(3,0), 
	"TP_IDPRODUCTO" NUMBER(3,0), 
	"TP_EXISTENCIA" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TABLA
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."TABLA" 
   (	"ID_TABLA" NUMBER(2,0), 
	"TABLA" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VE_DETALLE_VENTA
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" 
   (	"DV_IDFACTURA" NUMBER(3,0), 
	"DV_IDPRODUCTO" NUMBER(3,0), 
	"DV_UNIDADES" NUMBER(2,0), 
	"DV_COSTODETALLE" NUMBER(9,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VE_FACTURA
--------------------------------------------------------

  CREATE TABLE "C##PROYECTDB"."VE_FACTURA" 
   (	"FAC_IDFACTURA" NUMBER(*,0), 
	"FAC_FECHAHORA_FACTURA" DATE, 
	"FAC_TIPO_PAGO" CHAR(1), 
	"FAC_SUBTOTAL" NUMBER(9,2), 
	"FAC_COSTO_TOTAL" NUMBER(9,2), 
	"FAC_DESC_TOTAL" NUMBER(9,2), 
	"FAC_IDTIENDA" NUMBER(3,0), 
	"FAC_IDCLIENTE" NUMBER(3,0), 
	"FAC_IDEMPLEADO" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Materialized View C##PROYECDTB_REP_EMPLEADO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECDTB_REP_EMPLEADO" ("EM_CODPLANILLA", "EM_NOMBRES", "EM_PAPELLIDO", "EM_SAPELLIDO", "EM_FECHA_ING", "EM_FECHA_FIN", "EM_SUELDO", "EM_SUPERIOR", "EM_TIENDA", "EM_CARGO", "EM_ESTADO", "EM_CLAVE", "EM_LOGIN")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "EM_EMPLEADO"."EM_CODPLANILLA" "EM_CODPLANILLA","EM_EMPLEADO"."EM_NOMBRES" "EM_NOMBRES","EM_EMPLEADO"."EM_PAPELLIDO" "EM_PAPELLIDO","EM_EMPLEADO"."EM_SAPELLIDO" "EM_SAPELLIDO","EM_EMPLEADO"."EM_FECHA_ING" "EM_FECHA_ING","EM_EMPLEADO"."EM_FECHA_FIN" "EM_FECHA_FIN","EM_EMPLEADO"."EM_SUELDO" "EM_SUELDO","EM_EMPLEADO"."EM_SUPERIOR" "EM_SUPERIOR","EM_EMPLEADO"."EM_TIENDA" "EM_TIENDA","EM_EMPLEADO"."EM_CARGO" "EM_CARGO","EM_EMPLEADO"."EM_ESTADO" "EM_ESTADO","EM_EMPLEADO"."EM_CLAVE" "EM_CLAVE","EM_EMPLEADO"."EM_LOGIN" "EM_LOGIN" FROM "EM_EMPLEADO"@"DB" "EM_EMPLEADO";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECDTB_REP_EMPLEADO"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECDTB_REP_EMPLEADO';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_PR_DESCUENTO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_DESCUENTO" ("DE_IDDESCUENTO", "DE_PORCENTAJE", "DE_FECHA_INICIO", "DE_FECHA_FIN")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "PR_DESCUENTO"."DE_IDDESCUENTO" "DE_IDDESCUENTO","PR_DESCUENTO"."DE_PORCENTAJE" "DE_PORCENTAJE","PR_DESCUENTO"."DE_FECHA_INICIO" "DE_FECHA_INICIO","PR_DESCUENTO"."DE_FECHA_FIN" "DE_FECHA_FIN" FROM "PR_DESCUENTO"@"DB" "PR_DESCUENTO";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_DESCUENTO"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_PR_DESCUENTO';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_PR_FABRICANTE
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_FABRICANTE" ("FA_IDFABRICANTE", "FA_FABRICANTE", "FA_IDPROVEEDOR")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "PR_FABRICANTE"."FA_IDFABRICANTE" "FA_IDFABRICANTE","PR_FABRICANTE"."FA_FABRICANTE" "FA_FABRICANTE","PR_FABRICANTE"."FA_IDPROVEEDOR" "FA_IDPROVEEDOR" FROM "PR_FABRICANTE"@"DB" "PR_FABRICANTE";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_FABRICANTE"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_PR_FABRICANTE';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_PR_PRODUCTO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_PRODUCTO" ("PR_IDPRODUCTO", "PR_DESCRIPCION", "PR_PRECIO", "PR_CANTMINIMA", "PR_ESTADO", "PR_MODELO", "PR_IDFABRICANTE", "PR_IDCATEGORIA", "PR_IDDESCUENTO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "PR_PRODUCTO"."PR_IDPRODUCTO" "PR_IDPRODUCTO","PR_PRODUCTO"."PR_DESCRIPCION" "PR_DESCRIPCION","PR_PRODUCTO"."PR_PRECIO" "PR_PRECIO","PR_PRODUCTO"."PR_CANTMINIMA" "PR_CANTMINIMA","PR_PRODUCTO"."PR_ESTADO" "PR_ESTADO","PR_PRODUCTO"."PR_MODELO" "PR_MODELO","PR_PRODUCTO"."PR_IDFABRICANTE" "PR_IDFABRICANTE","PR_PRODUCTO"."PR_IDCATEGORIA" "PR_IDCATEGORIA","PR_PRODUCTO"."PR_IDDESCUENTO" "PR_IDDESCUENTO" FROM "PR_PRODUCTO"@"DB" "PR_PRODUCTO";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_PRODUCTO"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_PR_PRODUCTO';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_PR_PROVEEDOR
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_PROVEEDOR" ("PRO_IDPROVEEDOR", "PRO_PROVEEDOR")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "PR_PROVEEDOR"."PRO_IDPROVEEDOR" "PRO_IDPROVEEDOR","PR_PROVEEDOR"."PRO_PROVEEDOR" "PRO_PROVEEDOR" FROM "PR_PROVEEDOR"@"DB" "PR_PROVEEDOR";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_PROVEEDOR"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_PR_PROVEEDOR';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_PR_TIENDA
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_TIENDA" ("TI_IDTIENDA", "TI_TIENDA", "TI_DIRECCION", "TI_IDCIUDAD", "TI_TELEFONO", "TI_NIT")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "PR_TIENDA"."TI_IDTIENDA" "TI_IDTIENDA","PR_TIENDA"."TI_TIENDA" "TI_TIENDA","PR_TIENDA"."TI_DIRECCION" "TI_DIRECCION","PR_TIENDA"."TI_IDCIUDAD" "TI_IDCIUDAD","PR_TIENDA"."TI_TELEFONO" "TI_TELEFONO","PR_TIENDA"."TI_NIT" "TI_NIT" FROM "PR_TIENDA"@"DB" "PR_TIENDA";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_TIENDA"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_PR_TIENDA';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_PR_TIENDA_PRODUCTO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_TIENDA_PRODUCTO" ("TP_IDTIENDA", "TP_IDPRODUCTO", "TP_EXISTENCIA")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "PR_TIENDA_PRODUCTO"."TP_IDTIENDA" "TP_IDTIENDA","PR_TIENDA_PRODUCTO"."TP_IDPRODUCTO" "TP_IDPRODUCTO","PR_TIENDA_PRODUCTO"."TP_EXISTENCIA" "TP_EXISTENCIA" FROM "PR_TIENDA_PRODUCTO"@"DB" "PR_TIENDA_PRODUCTO";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_PR_TIENDA_PRODUCTO"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_PR_TIENDA_PRODUCTO';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_CL_CIUDAD
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_CIUDAD" ("CD_IDCIUDAD", "CD_IDDEPTO", "CD_IDPAIS", "CD_CIUDAD")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "CL_CIUDAD"."CD_IDCIUDAD" "CD_IDCIUDAD","CL_CIUDAD"."CD_IDDEPTO" "CD_IDDEPTO","CL_CIUDAD"."CD_IDPAIS" "CD_IDPAIS","CL_CIUDAD"."CD_CIUDAD" "CD_CIUDAD" FROM "CL_CIUDAD"@"DB" "CL_CIUDAD";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_CIUDAD"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_CL_CIUDAD';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_CL_CLIENTE
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_CLIENTE" ("CL_IDCLIENTE", "CL_TIPODOCUMENTO", "CL_NUMDOCUMENTO", "CL_NOMBRES", "CL_PAPELLIDO", "CL_SAPELLIDO", "CL_PROFESION", "CL_EMAIL", "CL_ESTADO", "CL_TIPOCLIENTE", "CL_IDENTTRIBUTARIA", "CL_USUARIO", "CL_CLAVE", "CL_FECHA_REGISTRO", "CL_FECHA_BAJA")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "CL_CLIENTE"."CL_IDCLIENTE" "CL_IDCLIENTE","CL_CLIENTE"."CL_TIPODOCUMENTO" "CL_TIPODOCUMENTO","CL_CLIENTE"."CL_NUMDOCUMENTO" "CL_NUMDOCUMENTO","CL_CLIENTE"."CL_NOMBRES" "CL_NOMBRES","CL_CLIENTE"."CL_PAPELLIDO" "CL_PAPELLIDO","CL_CLIENTE"."CL_SAPELLIDO" "CL_SAPELLIDO","CL_CLIENTE"."CL_PROFESION" "CL_PROFESION","CL_CLIENTE"."CL_EMAIL" "CL_EMAIL","CL_CLIENTE"."CL_ESTADO" "CL_ESTADO","CL_CLIENTE"."CL_TIPOCLIENTE" "CL_TIPOCLIENTE","CL_CLIENTE"."CL_IDENTTRIBUTARIA" "CL_IDENTTRIBUTARIA","CL_CLIENTE"."CL_USUARIO" "CL_USUARIO","CL_CLIENTE"."CL_CLAVE" "CL_CLAVE","CL_CLIENTE"."CL_FECHA_REGISTRO" "CL_FECHA_REGISTRO","CL_CLIENTE"."CL_FECHA_BAJA" "CL_FECHA_BAJA" FROM "CL_CLIENTE"@"DB" "CL_CLIENTE";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_CLIENTE"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_CL_CLIENTE';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_CL_DEPTO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_DEPTO" ("DP_IDDEPTO", "DP_IDPAIS", "DP_DEPTO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "CL_DEPTO"."DP_IDDEPTO" "DP_IDDEPTO","CL_DEPTO"."DP_IDPAIS" "DP_IDPAIS","CL_DEPTO"."DP_DEPTO" "DP_DEPTO" FROM "CL_DEPTO"@"DB" "CL_DEPTO";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_DEPTO"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_CL_DEPTO';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_CL_DIRECCION
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_DIRECCION" ("DI_TIPODIRECCION", "DI_CLIENTE", "DI_DIRECCION", "DI_CIUDAD")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "CL_DIRECCION"."DI_TIPODIRECCION" "DI_TIPODIRECCION","CL_DIRECCION"."DI_CLIENTE" "DI_CLIENTE","CL_DIRECCION"."DI_DIRECCION" "DI_DIRECCION","CL_DIRECCION"."DI_CIUDAD" "DI_CIUDAD" FROM "CL_DIRECCION"@"DB" "CL_DIRECCION";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_DIRECCION"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_CL_DIRECCION';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_CL_PAIS
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_PAIS" ("PA_IDPAIS", "PA_PAIS", "PA_IDIDIOMA")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "CL_PAIS"."PA_IDPAIS" "PA_IDPAIS","CL_PAIS"."PA_PAIS" "PA_PAIS","CL_PAIS"."PA_IDIDIOMA" "PA_IDIDIOMA" FROM "CL_PAIS"@"DB" "CL_PAIS";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_PAIS"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_CL_PAIS';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_CL_PROFESION
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_PROFESION" ("PR_IDPROFESION", "PR_PROFESION")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "CL_PROFESION"."PR_IDPROFESION" "PR_IDPROFESION","CL_PROFESION"."PR_PROFESION" "PR_PROFESION" FROM "CL_PROFESION"@"DB" "CL_PROFESION";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_PROFESION"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_CL_PROFESION';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_CL_TELEFONO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_TELEFONO" ("TE_TIPOTELEFONO", "TE_IDCLIENTE", "TE_TELEFONO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "CL_TELEFONO"."TE_TIPOTELEFONO" "TE_TIPOTELEFONO","CL_TELEFONO"."TE_IDCLIENTE" "TE_IDCLIENTE","CL_TELEFONO"."TE_TELEFONO" "TE_TELEFONO" FROM "CL_TELEFONO"@"DB" "CL_TELEFONO";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_CL_TELEFONO"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_CL_TELEFONO';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_EM_CARGO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_EM_CARGO" ("CAR_IDCARGO", "CAR_CARGO", "CAR_CARGO_SUP")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "EM_CARGO"."CAR_IDCARGO" "CAR_IDCARGO","EM_CARGO"."CAR_CARGO" "CAR_CARGO","EM_CARGO"."CAR_CARGO_SUP" "CAR_CARGO_SUP" FROM "EM_CARGO"@"DB" "EM_CARGO";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_EM_CARGO"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_EM_CARGO';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_REP_PR_CATEGORIA
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_PR_CATEGORIA" ("CA_IDCATEGORIA", "CA_CATEGORIA", "CA_IDPADRE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "PR_CATEGORIA"."CA_IDCATEGORIA" "CA_IDCATEGORIA","PR_CATEGORIA"."CA_CATEGORIA" "CA_CATEGORIA","PR_CATEGORIA"."CA_IDPADRE" "CA_IDPADRE" FROM "PR_CATEGORIA"@"DB" "PR_CATEGORIA";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_REP_PR_CATEGORIA"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_REP_PR_CATEGORIA';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_VE_DETALLE_VENTA
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_VE_DETALLE_VENTA" ("DV_IDFACTURA", "DV_IDPRODUCTO", "DV_UNIDADES", "DV_COSTODETALLE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "VE_DETALLE_VENTA"."DV_IDFACTURA" "DV_IDFACTURA","VE_DETALLE_VENTA"."DV_IDPRODUCTO" "DV_IDPRODUCTO","VE_DETALLE_VENTA"."DV_UNIDADES" "DV_UNIDADES","VE_DETALLE_VENTA"."DV_COSTODETALLE" "DV_COSTODETALLE" FROM "VE_DETALLE_VENTA"@"DB" "VE_DETALLE_VENTA";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_VE_DETALLE_VENTA"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_VE_DETALLE_VENTA';
--------------------------------------------------------
--  DDL for Materialized View C##PROYECTDB_VE_FACTURA
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_VE_FACTURA" ("FAC_IDFACTURA", "FAC_FECHAHORA_FACTURA", "FAC_TIPO_PAGO", "FAC_SUBTOTAL", "FAC_COSTO_TOTAL", "FAC_DESC_TOTAL", "FAC_IDTIENDA", "FAC_IDCLIENTE", "FAC_IDEMPLEADO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/(24*60)
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "VE_FACTURA"."FAC_IDFACTURA" "FAC_IDFACTURA","VE_FACTURA"."FAC_FECHAHORA_FACTURA" "FAC_FECHAHORA_FACTURA","VE_FACTURA"."FAC_TIPO_PAGO" "FAC_TIPO_PAGO","VE_FACTURA"."FAC_SUBTOTAL" "FAC_SUBTOTAL","VE_FACTURA"."FAC_COSTO_TOTAL" "FAC_COSTO_TOTAL","VE_FACTURA"."FAC_DESC_TOTAL" "FAC_DESC_TOTAL","VE_FACTURA"."FAC_IDTIENDA" "FAC_IDTIENDA","VE_FACTURA"."FAC_IDCLIENTE" "FAC_IDCLIENTE","VE_FACTURA"."FAC_IDEMPLEADO" "FAC_IDEMPLEADO" FROM "VE_FACTURA"@"DB" "VE_FACTURA";

   COMMENT ON MATERIALIZED VIEW "C##PROYECTDB"."C##PROYECTDB_VE_FACTURA"  IS 'snapshot table for snapshot C##PROYECTDB.C##PROYECTDB_VE_FACTURA';
REM INSERTING into C##PROYECTDB.CATALOGO
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.CL_CIUDAD
SET DEFINE OFF;
Insert into C##PROYECTDB.CL_CIUDAD (CD_IDCIUDAD,CD_IDDEPTO,CD_IDPAIS,CD_CIUDAD) values ('1','1','1','Ciudad de Guatemala');
REM INSERTING into C##PROYECTDB.CL_CLIENTE
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.CL_DEPTO
SET DEFINE OFF;
Insert into C##PROYECTDB.CL_DEPTO (DP_IDDEPTO,DP_IDPAIS,DP_DEPTO) values ('1','1','Guatemala');
REM INSERTING into C##PROYECTDB.CL_DIRECCION
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.CL_PAIS
SET DEFINE OFF;
Insert into C##PROYECTDB.CL_PAIS (PA_IDPAIS,PA_PAIS,PA_IDIDIOMA) values ('1','Guatemala','1');
REM INSERTING into C##PROYECTDB.CL_PROFESION
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.CL_TELEFONO
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.EM_CARGO
SET DEFINE OFF;
Insert into C##PROYECTDB.EM_CARGO (CAR_IDCARGO,CAR_CARGO,CAR_CARGO_SUP) values ('1','super usuario','1');
Insert into C##PROYECTDB.EM_CARGO (CAR_IDCARGO,CAR_CARGO,CAR_CARGO_SUP) values ('2','Director General','2');
Insert into C##PROYECTDB.EM_CARGO (CAR_IDCARGO,CAR_CARGO,CAR_CARGO_SUP) values ('3','Gerente de RRHH','2');
Insert into C##PROYECTDB.EM_CARGO (CAR_IDCARGO,CAR_CARGO,CAR_CARGO_SUP) values ('4','Jefe de RRHH','3');
REM INSERTING into C##PROYECTDB.EM_EMPLEADO
SET DEFINE OFF;
Insert into C##PROYECTDB.EM_EMPLEADO (EM_CODPLANILLA,EM_NOMBRES,EM_PAPELLIDO,EM_SAPELLIDO,EM_FECHA_ING,EM_FECHA_FIN,EM_SUELDO,EM_SUPERIOR,EM_TIENDA,EM_CARGO,EM_ESTADO,EM_CLAVE,EM_LOGIN) values ('0','super','administrador',null,to_date('01/04/18','DD/MM/RR'),null,'0','0','1','1','3','proyectdb','sa');
Insert into C##PROYECTDB.EM_EMPLEADO (EM_CODPLANILLA,EM_NOMBRES,EM_PAPELLIDO,EM_SAPELLIDO,EM_FECHA_ING,EM_FECHA_FIN,EM_SUELDO,EM_SUPERIOR,EM_TIENDA,EM_CARGO,EM_ESTADO,EM_CLAVE,EM_LOGIN) values ('1','Sergio Antonio','Segovia','Ruano',to_date('01/04/18','DD/MM/RR'),null,'25000','1','1','2','1','proyectdb','ssegoviar');
Insert into C##PROYECTDB.EM_EMPLEADO (EM_CODPLANILLA,EM_NOMBRES,EM_PAPELLIDO,EM_SAPELLIDO,EM_FECHA_ING,EM_FECHA_FIN,EM_SUELDO,EM_SUPERIOR,EM_TIENDA,EM_CARGO,EM_ESTADO,EM_CLAVE,EM_LOGIN) values ('2','Rigoberto Estuardo','Hurtado','Santa Cruz',to_date('01/04/18','DD/MM/RR'),null,'20000','1','1','3','1','proyectdb','rhurtadosc');
Insert into C##PROYECTDB.EM_EMPLEADO (EM_CODPLANILLA,EM_NOMBRES,EM_PAPELLIDO,EM_SAPELLIDO,EM_FECHA_ING,EM_FECHA_FIN,EM_SUELDO,EM_SUPERIOR,EM_TIENDA,EM_CARGO,EM_ESTADO,EM_CLAVE,EM_LOGIN) values ('3','Kevin Rodolfo','Morales','Hernandez',to_date('01/04/18','DD/MM/RR'),null,'15000','2','1','4','1','proyectdb','kmoralesh');
Insert into C##PROYECTDB.EM_EMPLEADO (EM_CODPLANILLA,EM_NOMBRES,EM_PAPELLIDO,EM_SAPELLIDO,EM_FECHA_ING,EM_FECHA_FIN,EM_SUELDO,EM_SUPERIOR,EM_TIENDA,EM_CARGO,EM_ESTADO,EM_CLAVE,EM_LOGIN) values ('5','Jorge Ruano','Sequen','Segovia',to_date('01/04/18','DD/MM/RR'),null,'15000','2','1','4','1','proyectdb','jsequens');
REM INSERTING into C##PROYECTDB.PR_CATEGORIA
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.PR_DESCUENTO
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.PR_FABRICANTE
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.PR_PRODUCTO
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.PR_PROVEEDOR
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.PR_TIENDA
SET DEFINE OFF;
Insert into C##PROYECTDB.PR_TIENDA (TI_IDTIENDA,TI_TIENDA,TI_DIRECCION,TI_IDCIUDAD,TI_TELEFONO,TI_NIT) values ('1','Recursos Humanos','Oficinas Centrales','1','85656585','1111111-1');
REM INSERTING into C##PROYECTDB.PR_TIENDA_PRODUCTO
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.TABLA
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.VE_DETALLE_VENTA
SET DEFINE OFF;
REM INSERTING into C##PROYECTDB.VE_FACTURA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CARGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_CARGO" ON "C##PROYECTDB"."EM_CARGO" ("CAR_IDCARGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_CATEGORIA" ON "C##PROYECTDB"."PR_CATEGORIA" ("CA_IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CIUDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_CIUDAD" ON "C##PROYECTDB"."CL_CIUDAD" ("CD_IDCIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_CLIENTE" ON "C##PROYECTDB"."CL_CLIENTE" ("CL_IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DEPTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_DEPTO" ON "C##PROYECTDB"."CL_DEPTO" ("DP_IDDEPTO", "DP_IDPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DESCUENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_DESCUENTO" ON "C##PROYECTDB"."PR_DESCUENTO" ("DE_IDDESCUENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DETALLE_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_DETALLE_VENTA" ON "C##PROYECTDB"."VE_DETALLE_VENTA" ("DV_IDFACTURA", "DV_IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DIRECCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_DIRECCION" ON "C##PROYECTDB"."CL_DIRECCION" ("DI_TIPODIRECCION", "DI_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_EMPLEADO" ON "C##PROYECTDB"."EM_EMPLEADO" ("EM_CODPLANILLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FABRICANTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_FABRICANTE" ON "C##PROYECTDB"."PR_FABRICANTE" ("FA_IDFABRICANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PAIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_PAIS" ON "C##PROYECTDB"."CL_PAIS" ("PA_IDPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_PRODUCTO" ON "C##PROYECTDB"."PR_PRODUCTO" ("PR_IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROFESION
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_PROFESION" ON "C##PROYECTDB"."CL_PROFESION" ("PR_IDPROFESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROVEEDOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_PROVEEDOR" ON "C##PROYECTDB"."PR_PROVEEDOR" ("PRO_IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TABLA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_TABLA" ON "C##PROYECTDB"."TABLA" ("ID_TABLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TELEFONO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_TELEFONO" ON "C##PROYECTDB"."CL_TELEFONO" ("TE_TIPOTELEFONO", "TE_IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIENDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_TIENDA" ON "C##PROYECTDB"."PR_TIENDA" ("TI_IDTIENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIENDA_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_TIENDA_PRODUCTO" ON "C##PROYECTDB"."PR_TIENDA_PRODUCTO" ("TP_IDTIENDA", "TP_IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."PK_VENTA" ON "C##PROYECTDB"."VE_FACTURA" ("FAC_IDFACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_1PK_EMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_1PK_EMPLEADO" ON "C##PROYECTDB"."C##PROYECDTB_REP_EMPLEADO" ("EM_CODPLANILLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_21PK_CIUDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_21PK_CIUDAD" ON "C##PROYECTDB"."C##PROYECTDB_REP_CL_CIUDAD" ("CD_IDCIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_22PK_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_22PK_CLIENTE" ON "C##PROYECTDB"."C##PROYECTDB_REP_CL_CLIENTE" ("CL_IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_23PK_DEPTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_23PK_DEPTO" ON "C##PROYECTDB"."C##PROYECTDB_REP_CL_DEPTO" ("DP_IDDEPTO", "DP_IDPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_24PK_DIRECCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_24PK_DIRECCION" ON "C##PROYECTDB"."C##PROYECTDB_REP_CL_DIRECCION" ("DI_TIPODIRECCION", "DI_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_25PK_PAIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_25PK_PAIS" ON "C##PROYECTDB"."C##PROYECTDB_REP_CL_PAIS" ("PA_IDPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_26PK_PROFESION
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_26PK_PROFESION" ON "C##PROYECTDB"."C##PROYECTDB_REP_CL_PROFESION" ("PR_IDPROFESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_27PK_TELEFONO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_27PK_TELEFONO" ON "C##PROYECTDB"."C##PROYECTDB_REP_CL_TELEFONO" ("TE_TIPOTELEFONO", "TE_IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_28PK_CARGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_28PK_CARGO" ON "C##PROYECTDB"."C##PROYECTDB_REP_EM_CARGO" ("CAR_IDCARGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_29PK_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_29PK_CATEGORIA" ON "C##PROYECTDB"."C##PROYECTDB_REP_PR_CATEGORIA" ("CA_IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_30PK_DESCUENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_30PK_DESCUENTO" ON "C##PROYECTDB"."C##PROYECTDB_PR_DESCUENTO" ("DE_IDDESCUENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_31PK_FABRICANTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_31PK_FABRICANTE" ON "C##PROYECTDB"."C##PROYECTDB_PR_FABRICANTE" ("FA_IDFABRICANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_32PK_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_32PK_PRODUCTO" ON "C##PROYECTDB"."C##PROYECTDB_PR_PRODUCTO" ("PR_IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_33PK_PROVEEDOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_33PK_PROVEEDOR" ON "C##PROYECTDB"."C##PROYECTDB_PR_PROVEEDOR" ("PRO_IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_34PK_TIENDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_34PK_TIENDA" ON "C##PROYECTDB"."C##PROYECTDB_PR_TIENDA" ("TI_IDTIENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_35PK_TIENDA_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_35PK_TIENDA_PRODUCTO" ON "C##PROYECTDB"."C##PROYECTDB_PR_TIENDA_PRODUCTO" ("TP_IDTIENDA", "TP_IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_36PK_DETALLE_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_36PK_DETALLE_VENTA" ON "C##PROYECTDB"."C##PROYECTDB_VE_DETALLE_VENTA" ("DV_IDFACTURA", "DV_IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C_SNAP$_37PK_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."SYS_C_SNAP$_37PK_VENTA" ON "C##PROYECTDB"."C##PROYECTDB_VE_FACTURA" ("FAC_IDFACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_CL_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTDB"."UQ_CL_CLIENTE" ON "C##PROYECTDB"."CL_CLIENTE" ("CL_NUMDOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CL_PROFESION
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_PROFESION" MODIFY ("PR_IDPROFESION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_PROFESION" MODIFY ("PR_PROFESION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_PROFESION" ADD CONSTRAINT "PK_PROFESION" PRIMARY KEY ("PR_IDPROFESION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_CATEGORIA" MODIFY ("CA_IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_CATEGORIA" MODIFY ("CA_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_CATEGORIA" ADD CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ("CA_IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_TELEFONO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_TELEFONO" MODIFY ("TE_TIPOTELEFONO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_TELEFONO" ADD CONSTRAINT "PK_TELEFONO" PRIMARY KEY ("TE_TIPOTELEFONO", "TE_IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EM_CARGO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."EM_CARGO" MODIFY ("CAR_IDCARGO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_CARGO" MODIFY ("CAR_CARGO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_CARGO" MODIFY ("CAR_CARGO_SUP" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_CARGO" ADD CONSTRAINT "PK_CARGO" PRIMARY KEY ("CAR_IDCARGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_PROVEEDOR" MODIFY ("PRO_IDPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PROVEEDOR" MODIFY ("PRO_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PROVEEDOR" ADD CONSTRAINT "PK_PROVEEDOR" PRIMARY KEY ("PRO_IDPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_DEPTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_DEPTO" MODIFY ("DP_IDDEPTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_DEPTO" MODIFY ("DP_IDPAIS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_DEPTO" MODIFY ("DP_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_DEPTO" ADD CONSTRAINT "PK_DEPTO" PRIMARY KEY ("DP_IDDEPTO", "DP_IDPAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" MODIFY ("PR_IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" MODIFY ("PR_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" MODIFY ("PR_PRECIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" MODIFY ("PR_CANTMINIMA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" MODIFY ("PR_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" MODIFY ("PR_IDFABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" MODIFY ("PR_IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" ADD CONSTRAINT "PK_PRODUCTO" PRIMARY KEY ("PR_IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."TABLA" MODIFY ("ID_TABLA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."TABLA" MODIFY ("TABLA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."TABLA" ADD CONSTRAINT "PK_TABLA" PRIMARY KEY ("ID_TABLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_TIENDA_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_TIENDA_PRODUCTO" MODIFY ("TP_IDTIENDA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA_PRODUCTO" MODIFY ("TP_IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA_PRODUCTO" ADD CONSTRAINT "PK_TIENDA_PRODUCTO" PRIMARY KEY ("TP_IDTIENDA", "TP_IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VE_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" MODIFY ("DV_IDFACTURA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" MODIFY ("DV_IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" MODIFY ("DV_UNIDADES" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" MODIFY ("DV_COSTODETALLE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" ADD CONSTRAINT "PK_DETALLE_VENTA" PRIMARY KEY ("DV_IDFACTURA", "DV_IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_PAIS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_PAIS" MODIFY ("PA_IDPAIS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_PAIS" MODIFY ("PA_PAIS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_PAIS" MODIFY ("PA_IDIDIOMA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_PAIS" ADD CONSTRAINT "PK_PAIS" PRIMARY KEY ("PA_IDPAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VE_FACTURA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_IDFACTURA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_FECHAHORA_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_TIPO_PAGO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_COSTO_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_DESC_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_IDTIENDA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" MODIFY ("FAC_IDEMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" ADD CONSTRAINT "PK_VENTA" PRIMARY KEY ("FAC_IDFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_DESCUENTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_DESCUENTO" MODIFY ("DE_IDDESCUENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_DESCUENTO" MODIFY ("DE_PORCENTAJE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_DESCUENTO" MODIFY ("DE_FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_DESCUENTO" ADD CONSTRAINT "PK_DESCUENTO" PRIMARY KEY ("DE_IDDESCUENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_CIUDAD
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_CIUDAD" MODIFY ("CD_IDCIUDAD" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CIUDAD" MODIFY ("CD_IDDEPTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CIUDAD" MODIFY ("CD_IDPAIS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CIUDAD" MODIFY ("CD_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CIUDAD" ADD CONSTRAINT "PK_CIUDAD" PRIMARY KEY ("CD_IDCIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_FABRICANTE
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_FABRICANTE" MODIFY ("FA_IDFABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_FABRICANTE" MODIFY ("FA_FABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_FABRICANTE" MODIFY ("FA_IDPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_FABRICANTE" ADD CONSTRAINT "PK_FABRICANTE" PRIMARY KEY ("FA_IDFABRICANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_CLIENTE
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_TIPODOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_NUMDOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_PAPELLIDO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_PROFESION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_TIPOCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_CLAVE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" MODIFY ("CL_FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" ADD CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("CL_IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" ADD CONSTRAINT "UQ_CL_CLIENTE" UNIQUE ("CL_NUMDOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_TIENDA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" MODIFY ("TI_IDTIENDA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" MODIFY ("TI_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" MODIFY ("TI_DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" MODIFY ("TI_IDCIUDAD" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" MODIFY ("TI_TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" MODIFY ("TI_NIT" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" ADD CONSTRAINT "PK_TIENDA" PRIMARY KEY ("TI_IDTIENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EM_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_CODPLANILLA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_PAPELLIDO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_FECHA_ING" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_SUELDO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_SUPERIOR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_CARGO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" MODIFY ("EM_CLAVE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" ADD CONSTRAINT "PK_EMPLEADO" PRIMARY KEY ("EM_CODPLANILLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_DIRECCION
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_DIRECCION" MODIFY ("DI_TIPODIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_DIRECCION" MODIFY ("DI_DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_DIRECCION" MODIFY ("DI_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTDB"."CL_DIRECCION" ADD CONSTRAINT "PK_DIRECCION" PRIMARY KEY ("DI_TIPODIRECCION", "DI_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATALOGO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CATALOGO" ADD CONSTRAINT "CATALOGO_TABLA_FK" FOREIGN KEY ("COD_TABLA")
	  REFERENCES "C##PROYECTDB"."TABLA" ("ID_TABLA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_CIUDAD
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_CIUDAD" ADD CONSTRAINT "CLCIUDAD_CLDEPTO_FK" FOREIGN KEY ("CD_IDDEPTO", "CD_IDPAIS")
	  REFERENCES "C##PROYECTDB"."CL_DEPTO" ("DP_IDDEPTO", "DP_IDPAIS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_CLIENTE
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_CLIENTE" ADD CONSTRAINT "CLIENTE_PROFESION_FK" FOREIGN KEY ("CL_PROFESION")
	  REFERENCES "C##PROYECTDB"."CL_PROFESION" ("PR_IDPROFESION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_DEPTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_DEPTO" ADD CONSTRAINT "CLDEPTO_CLPAIS_FK" FOREIGN KEY ("DP_IDPAIS")
	  REFERENCES "C##PROYECTDB"."CL_PAIS" ("PA_IDPAIS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_DIRECCION
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_DIRECCION" ADD CONSTRAINT "DIRECCION_CIUDAD_FK" FOREIGN KEY ("DI_CIUDAD")
	  REFERENCES "C##PROYECTDB"."CL_CIUDAD" ("CD_IDCIUDAD") ENABLE;
  ALTER TABLE "C##PROYECTDB"."CL_DIRECCION" ADD CONSTRAINT "DIRECCION_CLIENTE_FK" FOREIGN KEY ("DI_CLIENTE")
	  REFERENCES "C##PROYECTDB"."CL_CLIENTE" ("CL_IDCLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_TELEFONO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."CL_TELEFONO" ADD CONSTRAINT "TELEFONO_CLIENTE_FK" FOREIGN KEY ("TE_IDCLIENTE")
	  REFERENCES "C##PROYECTDB"."CL_CLIENTE" ("CL_IDCLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EM_CARGO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."EM_CARGO" ADD CONSTRAINT "CARGO_CARGOSUP_FK" FOREIGN KEY ("CAR_IDCARGO")
	  REFERENCES "C##PROYECTDB"."EM_CARGO" ("CAR_IDCARGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EM_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" ADD CONSTRAINT "EMPLEADO_CARGO_FK" FOREIGN KEY ("EM_CARGO")
	  REFERENCES "C##PROYECTDB"."EM_CARGO" ("CAR_IDCARGO") ENABLE;
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" ADD CONSTRAINT "EMPLEADO_TIENDA_FK" FOREIGN KEY ("EM_TIENDA")
	  REFERENCES "C##PROYECTDB"."PR_TIENDA" ("TI_IDTIENDA") ENABLE;
  ALTER TABLE "C##PROYECTDB"."EM_EMPLEADO" ADD CONSTRAINT "EMPLEADO_SUPERIOR_FK" FOREIGN KEY ("EM_SUPERIOR")
	  REFERENCES "C##PROYECTDB"."EM_EMPLEADO" ("EM_CODPLANILLA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PR_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_CATEGORIA" ADD CONSTRAINT "CATEGORIAH_CATEGORIAP_FK" FOREIGN KEY ("CA_IDPADRE")
	  REFERENCES "C##PROYECTDB"."PR_CATEGORIA" ("CA_IDCATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PR_FABRICANTE
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_FABRICANTE" ADD CONSTRAINT "FABRICANTE_PROVEEDOR_FK" FOREIGN KEY ("FA_IDPROVEEDOR")
	  REFERENCES "C##PROYECTDB"."PR_PROVEEDOR" ("PRO_IDPROVEEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PR_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" ADD CONSTRAINT "PRODUCTO_FABRICANTE_FK" FOREIGN KEY ("PR_IDFABRICANTE")
	  REFERENCES "C##PROYECTDB"."PR_FABRICANTE" ("FA_IDFABRICANTE") ENABLE;
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" ADD CONSTRAINT "PRODUCTO_CATEGORIA_FK" FOREIGN KEY ("PR_IDCATEGORIA")
	  REFERENCES "C##PROYECTDB"."PR_CATEGORIA" ("CA_IDCATEGORIA") ENABLE;
  ALTER TABLE "C##PROYECTDB"."PR_PRODUCTO" ADD CONSTRAINT "PRODUCTO_DESCUENTO_FK" FOREIGN KEY ("PR_IDDESCUENTO")
	  REFERENCES "C##PROYECTDB"."PR_DESCUENTO" ("DE_IDDESCUENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PR_TIENDA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_TIENDA" ADD CONSTRAINT "TIENDA_CIUDAD_FK" FOREIGN KEY ("TI_IDCIUDAD")
	  REFERENCES "C##PROYECTDB"."CL_CIUDAD" ("CD_IDCIUDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PR_TIENDA_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."PR_TIENDA_PRODUCTO" ADD CONSTRAINT "TIENDA_PRODUCTO_FK" FOREIGN KEY ("TP_IDTIENDA")
	  REFERENCES "C##PROYECTDB"."PR_TIENDA" ("TI_IDTIENDA") ENABLE;
  ALTER TABLE "C##PROYECTDB"."PR_TIENDA_PRODUCTO" ADD CONSTRAINT "PRODUCTO_TIENDA_FK" FOREIGN KEY ("TP_IDPRODUCTO")
	  REFERENCES "C##PROYECTDB"."PR_PRODUCTO" ("PR_IDPRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VE_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" ADD CONSTRAINT "PRODUCTO_FACTURA_FK" FOREIGN KEY ("DV_IDFACTURA")
	  REFERENCES "C##PROYECTDB"."VE_FACTURA" ("FAC_IDFACTURA") ENABLE;
  ALTER TABLE "C##PROYECTDB"."VE_DETALLE_VENTA" ADD CONSTRAINT "FACTURA_PRODUCTO_FK" FOREIGN KEY ("DV_IDPRODUCTO")
	  REFERENCES "C##PROYECTDB"."PR_PRODUCTO" ("PR_IDPRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VE_FACTURA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" ADD CONSTRAINT "VENTA_TIENDA_FK" FOREIGN KEY ("FAC_IDTIENDA")
	  REFERENCES "C##PROYECTDB"."PR_TIENDA" ("TI_IDTIENDA") ENABLE;
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" ADD CONSTRAINT "VENTA_CLIENTE_FK" FOREIGN KEY ("FAC_IDCLIENTE")
	  REFERENCES "C##PROYECTDB"."CL_CLIENTE" ("CL_IDCLIENTE") ENABLE;
  ALTER TABLE "C##PROYECTDB"."VE_FACTURA" ADD CONSTRAINT "VENTA_EMPLEADO_FK" FOREIGN KEY ("FAC_IDEMPLEADO")
	  REFERENCES "C##PROYECTDB"."EM_EMPLEADO" ("EM_CODPLANILLA") ENABLE;
